<p>id<?php echo $profile_item['id'] ?></p>
<p>user_login<?php echo $profile_item['user_login'] ?></p>
<p>user_first_name<?php echo $profile_item['user_first_name'] ?></p>
<p>user_last_name<?php echo $profile_item['user_last_name'] ?></p>
<p>user_grad_year<?php echo $profile_item['user_grad_year'] ?></p>
<p>user_status<?php echo $profile_item['user_status'] ?></p>
<p>user_email<?php echo $profile_item['user_email'] ?></p>
<p>user_gender<?php echo $profile_item['user_gender'] ?></p>
<p>user_description<?php echo $profile_item['user_description'] ?></p>
<p>user_major1<?php echo $profile_item['user_major1'] ?></p>
<p>user_major2<?php echo $profile_item['user_major2'] ?></p>